;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Quest.Collected.1",DevComment="")
GameplayTagList=(Tag="Quest.Collected.2",DevComment="")
GameplayTagList=(Tag="Quest.Collected.3",DevComment="")
GameplayTagList=(Tag="Quest.Collected.2.A",DevComment="")
GameplayTagList=(Tag="Quest.Collected.2.B",DevComment="")
GameplayTagList=(Tag="Quest.Mission.1",DevComment="")
GameplayTagList=(Tag="Quest.Mission.2",DevComment="")
GameplayTagList=(Tag="Quest.Mission.3",DevComment="")

